x = input(" Enter Your Number \n ")
print(x)

y = int( x * 1 )
print(y)
y = (" * 2 = " + x * 2)
print(x + y)
y = (" * 3 = " + x * 3 )
print(x + y)
y = (" * 4 = " + x)
print(x + y)
y = (" * 5 = " + x)
print(x + y)
y = (" * 6 = " + x)
print(x + y)
y = (" * 7 = " + x)
print(x + y)
y = (" * 8 = " + x)
print(x + y)
y = (" * 9 = " + x)
print(x + y)
y = (x, * 10, x *10)
print(x + y)
